/**
 * Generated by orval v7.16.0 🍺
 * Do not edit manually.
 * Genkit AI Service API
 * AI 模型提供商管理服务 API 文档
提供模型提供商、模型信息和参数规则的查询接口
 * OpenAPI spec version: 1.0.0
 */
import type {
  AnyDataResponse,
  CreateSpaceRequestSwagger,
  DeleteLexiangSpacesIdPathParameters,
  GetLexiangSpacesIdPathParameters,
  GetLexiangSpacesParams,
  LexiangSpaceDataResponse,
  LexiangSpaceListDataResponse,
  PutLexiangSpacesIdBody,
  PutLexiangSpacesIdPathParameters,
} from '../../../types/api';
import { orvalMutator } from '../../../utils/orval-mutator';

export const getLexiangKnowledgeBase = () => {
  /**
   * 获取指定团队下的知识库列表，支持分页
   * @summary 获取知识库列表
   */
  const getLexiangSpaces = (params: GetLexiangSpacesParams) => {
    return orvalMutator<LexiangSpaceListDataResponse>({
      url: `/lexiang/spaces`,
      method: 'GET',
      params,
    });
  };
  /**
   * 在指定团队下创建新的知识库
   * @summary 创建知识库
   */
  const postLexiangSpaces = (createSpaceRequestSwagger: CreateSpaceRequestSwagger) => {
    return orvalMutator<LexiangSpaceDataResponse>({
      url: `/lexiang/spaces`,
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      data: createSpaceRequestSwagger,
    });
  };
  /**
   * 删除指定的知识库
   * @summary 删除知识库
   */
  const deleteLexiangSpacesId = ({ id }: DeleteLexiangSpacesIdPathParameters) => {
    return orvalMutator<AnyDataResponse>({ url: `/lexiang/spaces/${id}`, method: 'DELETE' });
  };
  /**
   * 根据知识库ID获取详细信息
   * @summary 获取知识库详情
   */
  const getLexiangSpacesId = ({ id }: GetLexiangSpacesIdPathParameters) => {
    return orvalMutator<LexiangSpaceDataResponse>({ url: `/lexiang/spaces/${id}`, method: 'GET' });
  };
  /**
   * 更新知识库名称
   * @summary 更新知识库
   */
  const putLexiangSpacesId = (
    { id }: PutLexiangSpacesIdPathParameters,
    putLexiangSpacesIdBody: PutLexiangSpacesIdBody,
  ) => {
    return orvalMutator<LexiangSpaceDataResponse>({
      url: `/lexiang/spaces/${id}`,
      method: 'PUT',
      headers: { 'Content-Type': 'application/json' },
      data: putLexiangSpacesIdBody,
    });
  };
  return {
    getLexiangSpaces,
    postLexiangSpaces,
    deleteLexiangSpacesId,
    getLexiangSpacesId,
    putLexiangSpacesId,
  };
};
export type GetLexiangSpacesResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getLexiangKnowledgeBase>['getLexiangSpaces']>>
>;
export type PostLexiangSpacesResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getLexiangKnowledgeBase>['postLexiangSpaces']>>
>;
export type DeleteLexiangSpacesIdResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getLexiangKnowledgeBase>['deleteLexiangSpacesId']>>
>;
export type GetLexiangSpacesIdResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getLexiangKnowledgeBase>['getLexiangSpacesId']>>
>;
export type PutLexiangSpacesIdResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getLexiangKnowledgeBase>['putLexiangSpacesId']>>
>;
