/**
 * Generated by orval v7.14.0 🍺
 * Do not edit manually.
 * Genkit AI Service API
 * AI 模型提供商管理服务 API 文档
提供模型提供商、模型信息和参数规则的查询接口
 * OpenAPI spec version: 1.0.0
 */
import type {
  GenkitAiServiceInternalModelAuthAuditListResponse,
  GetAuditAuthParams,
} from '../../../types/api'

import { orvalMutator } from '../../../utils/orval-mutator'

export const getAudit = () => {
  /**
   * 查询认证审计日志，支持多条件过滤和分页
   * @summary 查询审计日志
   */
  const getAuditAuth = (params?: GetAuditAuthParams) => {
    return orvalMutator<GenkitAiServiceInternalModelAuthAuditListResponse>({
      url: `/audit/auth`,
      method: 'GET',
      params,
    })
  }
  return { getAuditAuth }
}
export type GetAuditAuthResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getAudit>['getAuditAuth']>>
>
