/**
 * Generated by orval v7.16.0 🍺
 * Do not edit manually.
 * Genkit AI Service API
 * AI 模型提供商管理服务 API 文档
提供模型提供商、模型信息和参数规则的查询接口
 * OpenAPI spec version: 1.0.0
 */
import type {
  GetLexiangFilesIdDownloadPathParameters,
  GetLexiangFilesIdPathParameters,
  LexiangDocFileDataResponse,
} from '../../../types/api';
import { orvalMutator } from '../../../utils/orval-mutator';

export const getLexiangDownload = () => {
  /**
   * 获取附件的详情信息，包含下载链接
   * @summary 获取附件详情
   */
  const getLexiangFilesId = ({ id }: GetLexiangFilesIdPathParameters) => {
    return orvalMutator<LexiangDocFileDataResponse>({ url: `/lexiang/files/${id}`, method: 'GET' });
  };
  /**
   * 下载附件内容
   * @summary 下载附件
   */
  const getLexiangFilesIdDownload = ({ id }: GetLexiangFilesIdDownloadPathParameters) => {
    return orvalMutator<Blob>({
      url: `/lexiang/files/${id}/download`,
      method: 'GET',
      responseType: 'blob',
    });
  };
  return { getLexiangFilesId, getLexiangFilesIdDownload };
};
export type GetLexiangFilesIdResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getLexiangDownload>['getLexiangFilesId']>>
>;
export type GetLexiangFilesIdDownloadResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getLexiangDownload>['getLexiangFilesIdDownload']>>
>;
