/**
 * Generated by orval v7.14.0 🍺
 * Do not edit manually.
 * Genkit AI Service API
 * AI 模型提供商管理服务 API 文档
提供模型提供商、模型信息和参数规则的查询接口
 * OpenAPI spec version: 1.0.0
 */
import type {
  GetProvidersProviderIdModelsModelIdParameterRulesPathParameters,
  GetProvidersProviderIdModelsModelIdPathParameters,
  GetProvidersProviderIdModelsPathParameters,
  GetProvidersProviderIdPathParameters,
  ModelDataResponse,
  ModelListDataResponse,
  ParameterRuleListDataResponse,
  ProviderDataResponse,
  ProviderListDataResponse,
} from '../../../types/api';
import { orvalMutator } from '../../../utils/orval-mutator';

export const getProviders = () => {
  /**
   * 获取系统中所有可用的模型提供商列表
   * @summary 获取所有提供商列表
   */
  const getProviders = () => {
    return orvalMutator<ProviderListDataResponse>({ url: `/providers`, method: 'GET' });
  };
  /**
   * 根据提供商ID获取详细信息
   * @summary 获取提供商详情
   */
  const getProvidersProviderId = ({ providerId }: GetProvidersProviderIdPathParameters) => {
    return orvalMutator<ProviderDataResponse>({ url: `/providers/${providerId}`, method: 'GET' });
  };
  /**
   * 获取指定提供商的所有可用模型列表
   * @summary 获取提供商的模型列表
   */
  const getProvidersProviderIdModels = ({
    providerId,
  }: GetProvidersProviderIdModelsPathParameters) => {
    return orvalMutator<ModelListDataResponse>({
      url: `/providers/${providerId}/models`,
      method: 'GET',
    });
  };
  /**
   * 获取指定提供商的指定模型的详细信息
   * @summary 获取模型详情
   */
  const getProvidersProviderIdModelsModelId = ({
    providerId,
    modelId,
  }: GetProvidersProviderIdModelsModelIdPathParameters) => {
    return orvalMutator<ModelDataResponse>({
      url: `/providers/${providerId}/models/${modelId}`,
      method: 'GET',
    });
  };
  /**
   * 获取指定模型的所有参数配置规则
   * @summary 获取模型参数规则
   */
  const getProvidersProviderIdModelsModelIdParameterRules = ({
    providerId,
    modelId,
  }: GetProvidersProviderIdModelsModelIdParameterRulesPathParameters) => {
    return orvalMutator<ParameterRuleListDataResponse>({
      url: `/providers/${providerId}/models/${modelId}/parameter-rules`,
      method: 'GET',
    });
  };
  return {
    getProviders,
    getProvidersProviderId,
    getProvidersProviderIdModels,
    getProvidersProviderIdModelsModelId,
    getProvidersProviderIdModelsModelIdParameterRules,
  };
};
export type GetProvidersResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getProviders>['getProviders']>>
>;
export type GetProvidersProviderIdResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getProviders>['getProvidersProviderId']>>
>;
export type GetProvidersProviderIdModelsResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getProviders>['getProvidersProviderIdModels']>>
>;
export type GetProvidersProviderIdModelsModelIdResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getProviders>['getProvidersProviderIdModelsModelId']>>
>;
export type GetProvidersProviderIdModelsModelIdParameterRulesResult = NonNullable<
  Awaited<
    ReturnType<ReturnType<typeof getProviders>['getProvidersProviderIdModelsModelIdParameterRules']>
  >
>;
