/**
 * Generated by orval v7.16.0 🍺
 * Do not edit manually.
 * Genkit AI Service API
 * AI 模型提供商管理服务 API 文档
提供模型提供商、模型信息和参数规则的查询接口
 * OpenAPI spec version: 1.0.0
 */
import type {
  AnyDataResponse,
  CreateSessionRequest,
  DeleteChatSessionsIdPathParameters,
  GetChatSessionsIdPathParameters,
  GetChatSessionsParams,
  GetChatSessionsSearchParams,
  PatchChatSessionsIdPathParameters,
  PostChatSessionsIdArchiveParams,
  PostChatSessionsIdArchivePathParameters,
  PostChatSessionsIdPinParams,
  PostChatSessionsIdPinPathParameters,
  SessionDataResponse,
  SessionListResponse,
  UpdateSessionRequest,
} from '../../../types/api';
import { orvalMutator } from '../../../utils/orval-mutator';

export const getSessions = () => {
  /**
   * 获取用户的会话列表，支持分页和过滤
   * @summary 获取会话列表
   */
  const getChatSessions = (params: GetChatSessionsParams) => {
    return orvalMutator<SessionListResponse>({ url: `/chat/sessions`, method: 'GET', params });
  };
  /**
   * 创建一个新的聊天会话
   * @summary 创建新会话
   */
  const postChatSessions = (createSessionRequest: CreateSessionRequest) => {
    return orvalMutator<SessionDataResponse>({
      url: `/chat/sessions`,
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      data: createSessionRequest,
    });
  };
  /**
   * 软删除指定的会话
   * @summary 删除会话
   */
  const deleteChatSessionsId = ({ id }: DeleteChatSessionsIdPathParameters) => {
    return orvalMutator<AnyDataResponse>({ url: `/chat/sessions/${id}`, method: 'DELETE' });
  };
  /**
   * 根据会话ID获取会话的详细信息
   * @summary 获取会话详情
   */
  const getChatSessionsId = ({ id }: GetChatSessionsIdPathParameters) => {
    return orvalMutator<SessionDataResponse>({ url: `/chat/sessions/${id}`, method: 'GET' });
  };
  /**
   * 更新会话的标题、配置等信息
   * @summary 更新会话
   */
  const patchChatSessionsId = (
    { id }: PatchChatSessionsIdPathParameters,
    updateSessionRequest: UpdateSessionRequest,
  ) => {
    return orvalMutator<SessionDataResponse>({
      url: `/chat/sessions/${id}`,
      method: 'PATCH',
      headers: { 'Content-Type': 'application/json' },
      data: updateSessionRequest,
    });
  };
  /**
   * 归档或取消归档指定的会话
   * @summary 归档会话
   */
  const postChatSessionsIdArchive = (
    { id }: PostChatSessionsIdArchivePathParameters,
    params: PostChatSessionsIdArchiveParams,
  ) => {
    return orvalMutator<AnyDataResponse>({
      url: `/chat/sessions/${id}/archive`,
      method: 'POST',
      params,
    });
  };
  /**
   * 置顶或取消置顶指定的会话
   * @summary 置顶会话
   */
  const postChatSessionsIdPin = (
    { id }: PostChatSessionsIdPinPathParameters,
    params: PostChatSessionsIdPinParams,
  ) => {
    return orvalMutator<AnyDataResponse>({
      url: `/chat/sessions/${id}/pin`,
      method: 'POST',
      params,
    });
  };
  /**
   * 根据关键词搜索会话
   * @summary 搜索会话
   */
  const getChatSessionsSearch = (params: GetChatSessionsSearchParams) => {
    return orvalMutator<SessionListResponse>({
      url: `/chat/sessions/search`,
      method: 'GET',
      params,
    });
  };
  return {
    getChatSessions,
    postChatSessions,
    deleteChatSessionsId,
    getChatSessionsId,
    patchChatSessionsId,
    postChatSessionsIdArchive,
    postChatSessionsIdPin,
    getChatSessionsSearch,
  };
};
export type GetChatSessionsResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getSessions>['getChatSessions']>>
>;
export type PostChatSessionsResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getSessions>['postChatSessions']>>
>;
export type DeleteChatSessionsIdResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getSessions>['deleteChatSessionsId']>>
>;
export type GetChatSessionsIdResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getSessions>['getChatSessionsId']>>
>;
export type PatchChatSessionsIdResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getSessions>['patchChatSessionsId']>>
>;
export type PostChatSessionsIdArchiveResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getSessions>['postChatSessionsIdArchive']>>
>;
export type PostChatSessionsIdPinResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getSessions>['postChatSessionsIdPin']>>
>;
export type GetChatSessionsSearchResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getSessions>['getChatSessionsSearch']>>
>;
