/**
 * Generated by orval v7.16.0 🍺
 * Do not edit manually.
 * Genkit AI Service API
 * AI 模型提供商管理服务 API 文档
提供模型提供商、模型信息和参数规则的查询接口
 * OpenAPI spec version: 1.0.0
 */
import type {
  AnyDataResponse,
  CreateSessionRequest,
  DeleteChatSessionsIdPathParameters,
  GetChatSessionsIdPathParameters,
  GetChatSessionsParams,
  GetChatSessionsSearchParams,
  PatchChatSessionsIdPathParameters,
  PostChatSessionsIdArchiveParams,
  PostChatSessionsIdArchivePathParameters,
  PostChatSessionsIdPinParams,
  PostChatSessionsIdPinPathParameters,
  SessionDataResponse,
  SessionListResponse,
  UpdateSessionRequest,
} from '../../../types/api';
import { orvalMutator } from '../../../utils/orval-mutator';

export const getSessions = () => {
  /**
   * 获取用户的会话列表，支持分页和过滤
   * @summary 获取会话列表
   */
  const getChatSessions = (params: GetChatSessionsParams) => {
    return orvalMutator<SessionListResponse>({ url: `/chat/sessions`, method: 'GET', params });
  };
  /**
 * 创建一个新的聊天会话。需要指定会话使用的AI模型名称（如 gpt-4、gemini-pro、qwen-turbo 等）。系统会根据当前租户ID和模型名称从 model_configurations 表中查询配置。

使用示例：
1. 创建使用 Azure OpenAI GPT-4 的会话：
```json
{
"title": "技术讨论",
"modelName": "gpt-4",
"systemPrompt": "你是一个专业的技术顾问",
"temperature": 0.7
}
```

2. 创建使用阿里云百炼 Qwen 的会话：
```json
{
"title": "中文写作助手",
"modelName": "qwen-turbo",
"systemPrompt": "你是一个专业的中文写作助手",
"temperature": 0.9
}
```

3. 创建使用 Google AI Gemini 的会话：
```json
{
"title": "代码分析",
"modelName": "gemini-pro",
"systemPrompt": "你是一个代码审查专家",
"temperature": 0.3
}
```
 * @summary 创建新会话
 */
  const postChatSessions = (createSessionRequest: CreateSessionRequest) => {
    return orvalMutator<SessionDataResponse>({
      url: `/chat/sessions`,
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      data: createSessionRequest,
    });
  };
  /**
   * 软删除指定的会话
   * @summary 删除会话
   */
  const deleteChatSessionsId = ({ id }: DeleteChatSessionsIdPathParameters) => {
    return orvalMutator<AnyDataResponse>({ url: `/chat/sessions/${id}`, method: 'DELETE' });
  };
  /**
   * 根据会话ID获取会话的详细信息
   * @summary 获取会话详情
   */
  const getChatSessionsId = ({ id }: GetChatSessionsIdPathParameters) => {
    return orvalMutator<SessionDataResponse>({ url: `/chat/sessions/${id}`, method: 'GET' });
  };
  /**
 * 更新会话的标题、配置等信息。可以通过 modelName 字段切换会话使用的AI模型。系统会根据当前租户ID和新的模型名称从 model_configurations 表中查询配置。

使用示例：
1. 只更新会话标题：
```json
{
"title": "新的会话标题"
}
```

2. 切换会话使用的模型（从 Gemini 切换到 GPT-4）：
```json
{
"modelName": "gpt-4",
"temperature": 0.8
}
```

3. 更新系统提示词和模型参数：
```json
{
"systemPrompt": "你是一个专业的Python编程助手",
"temperature": 0.5,
"topP": 0.95
}
```

4. 同时更新多个字段：
```json
{
"title": "Python编程助手",
"modelName": "qwen-turbo",
"systemPrompt": "你是一个专业的Python编程助手",
"temperature": 0.7
}
```
 * @summary 更新会话
 */
  const patchChatSessionsId = (
    { id }: PatchChatSessionsIdPathParameters,
    updateSessionRequest: UpdateSessionRequest,
  ) => {
    return orvalMutator<SessionDataResponse>({
      url: `/chat/sessions/${id}`,
      method: 'PATCH',
      headers: { 'Content-Type': 'application/json' },
      data: updateSessionRequest,
    });
  };
  /**
   * 归档或取消归档指定的会话
   * @summary 归档会话
   */
  const postChatSessionsIdArchive = (
    { id }: PostChatSessionsIdArchivePathParameters,
    params: PostChatSessionsIdArchiveParams,
  ) => {
    return orvalMutator<AnyDataResponse>({
      url: `/chat/sessions/${id}/archive`,
      method: 'POST',
      params,
    });
  };
  /**
   * 置顶或取消置顶指定的会话
   * @summary 置顶会话
   */
  const postChatSessionsIdPin = (
    { id }: PostChatSessionsIdPinPathParameters,
    params: PostChatSessionsIdPinParams,
  ) => {
    return orvalMutator<AnyDataResponse>({
      url: `/chat/sessions/${id}/pin`,
      method: 'POST',
      params,
    });
  };
  /**
   * 根据关键词搜索会话
   * @summary 搜索会话
   */
  const getChatSessionsSearch = (params: GetChatSessionsSearchParams) => {
    return orvalMutator<SessionListResponse>({
      url: `/chat/sessions/search`,
      method: 'GET',
      params,
    });
  };
  return {
    getChatSessions,
    postChatSessions,
    deleteChatSessionsId,
    getChatSessionsId,
    patchChatSessionsId,
    postChatSessionsIdArchive,
    postChatSessionsIdPin,
    getChatSessionsSearch,
  };
};
export type GetChatSessionsResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getSessions>['getChatSessions']>>
>;
export type PostChatSessionsResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getSessions>['postChatSessions']>>
>;
export type DeleteChatSessionsIdResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getSessions>['deleteChatSessionsId']>>
>;
export type GetChatSessionsIdResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getSessions>['getChatSessionsId']>>
>;
export type PatchChatSessionsIdResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getSessions>['patchChatSessionsId']>>
>;
export type PostChatSessionsIdArchiveResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getSessions>['postChatSessionsIdArchive']>>
>;
export type PostChatSessionsIdPinResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getSessions>['postChatSessionsIdPin']>>
>;
export type GetChatSessionsSearchResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getSessions>['getChatSessionsSearch']>>
>;
