/**
 * Generated by orval v7.14.0 🍺
 * Do not edit manually.
 * Genkit AI Service API
 * AI 模型提供商管理服务 API 文档
提供模型提供商、模型信息和参数规则的查询接口
 * OpenAPI spec version: 1.0.0
 */
import type { InternalApiHandlerHealthStatusResponse } from '../../../types/api'

import { orvalMutator } from '../../../utils/orval-mutator'

export const getHealth = () => {
  /**
   * 检查服务及其依赖项的健康状态
   * @summary 健康检查
   */
  const getHealth = () => {
    return orvalMutator<InternalApiHandlerHealthStatusResponse>({
      url: `/health`,
      method: 'GET',
    })
  }
  return { getHealth }
}
export type GetHealthResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getHealth>['getHealth']>>
>
