/**
 * Generated by orval v7.16.0 🍺
 * Do not edit manually.
 * Genkit AI Service API
 * AI 模型提供商管理服务 API 文档
提供模型提供商、模型信息和参数规则的查询接口
 * OpenAPI spec version: 1.0.0
 */
import type {
  CreateModelConfigurationRequest,
  DeleteModelConfigurationsIdPathParameters,
  GetModelConfigurationsIdPathParameters,
  GetModelConfigurationsParams,
  PatchModelConfigurationsIdStatusPathParameters,
  PostModelConfigurationsIdValidatePathParameters,
  PutModelConfigurationsIdPathParameters,
  ResponseDataAny,
  ResponseDataArrayModelModelConfiguration,
  ResponseDataModelModelConfiguration,
  ResponseDataModelValidationResult,
  ResponsePaginationDataArrayModelModelConfiguration,
  UpdateModelConfigurationRequest,
  UpdateStatusRequest,
} from '../../../types/api';
import { orvalMutator } from '../../../utils/orval-mutator';

export const getModelConfiguration = () => {
  /**
 * 获取模型配置列表，支持分页和租户过滤

**权限要求**：
- 平台管理员（system_admin）：可以查看所有租户的配置或指定租户的配置
- 租户管理员（tenant_admin）：只能查看自己租户下的配置

**tenantId 查询参数使用规则**：
- 租户管理员：
- tenantId 参数会被忽略
- 始终只返回当前用户所属租户下的配置列表
- 平台管理员：
- 如果提供 tenantId，返回指定租户下的配置列表
- 如果不提供 tenantId，返回所有租户下的配置列表

**参数说明**：
- pageNo: 页码（从1开始，默认1）
- pageSize: 每页大小（1-100，默认20）
- tenantId: 租户ID（可选，UUID格式，仅平台管理员可用）

**注意事项**：
- 租户管理员调用此接口时，tenantId 参数会被忽略
- 租户管理员始终只能看到自己租户下的配置
 * @summary 获取模型配置列表
 */
  const getModelConfigurations = (params?: GetModelConfigurationsParams) => {
    return orvalMutator<ResponsePaginationDataArrayModelModelConfiguration>({
      url: `/model-configurations`,
      method: 'GET',
      params,
    });
  };
  /**
 * 创建新的模型配置，支持可选的租户ID参数

**权限要求**：
- 平台管理员（system_admin）：可以在任意租户下创建模型配置
- 租户管理员（tenant_admin）：只能在自己的租户下创建模型配置

**tenantId 参数使用规则**：
- 租户管理员：
- 如果不提供 tenantId，系统自动使用当前用户的租户ID
- 如果提供 tenantId，必须与当前用户的租户ID匹配，否则返回 403 错误
- 平台管理员：
- 必须提供 tenantId 参数
- 可以指定任意有效的租户ID

**参数说明**：
- tenantId: 租户ID（可选，UUID格式）
- name: 配置名称（必填）
- model: 模型标识（必填，如：gpt-4、claude-3-opus）
- modelProvider: 模型提供商（必填，可选值：openai、anthropic、googlegenai、azureopenai、bianlian、custom_openai）
- baseUrl: API基础URL（可选，用于自定义端点）
- apiKey: API密钥（必填，将被加密存储）
- queryParams: 查询参数（可选，JSON格式）
 * @summary 创建模型配置
 */
  const postModelConfigurations = (
    createModelConfigurationRequest: CreateModelConfigurationRequest,
  ) => {
    return orvalMutator<ResponseDataModelModelConfiguration>({
      url: `/model-configurations`,
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      data: createModelConfigurationRequest,
    });
  };
  /**
 * 软删除指定的模型配置

**权限要求**：
- 平台管理员（system_admin）：可以删除任意租户下的模型配置
- 租户管理员（tenant_admin）：只能删除自己租户下的模型配置

**访问权限验证**：
- 系统会自动查询目标配置所属的租户
- 租户管理员尝试删除其他租户的配置时，将收到 403 权限不足错误
- 平台管理员可以删除任意租户的配置，无需额外验证

**功能说明**：
- 执行软删除操作（设置 is_deleted=true）
- 删除后的配置数据仍保留在数据库中，但不再可见

**参数说明**：
- id: 配置ID（UUID格式）
 * @summary 删除模型配置
 */
  const deleteModelConfigurationsId = ({ id }: DeleteModelConfigurationsIdPathParameters) => {
    return orvalMutator<ResponseDataAny>({ url: `/model-configurations/${id}`, method: 'DELETE' });
  };
  /**
 * 根据配置ID获取模型配置详细信息

**权限要求**：
- 平台管理员（system_admin）：可以查看任意租户下的模型配置
- 租户管理员（tenant_admin）：只能查看自己租户下的模型配置

**访问权限验证**：
- 系统会自动查询目标配置所属的租户
- 租户管理员尝试查看其他租户的配置时，将收到 403 权限不足错误
- 平台管理员可以查看任意租户的配置，无需额外验证

**参数说明**：
- id: 配置ID（UUID格式）
 * @summary 获取模型配置详情
 */
  const getModelConfigurationsId = ({ id }: GetModelConfigurationsIdPathParameters) => {
    return orvalMutator<ResponseDataModelModelConfiguration>({
      url: `/model-configurations/${id}`,
      method: 'GET',
    });
  };
  /**
 * 更新模型配置信息

**权限要求**：
- 平台管理员（system_admin）：可以更新任意租户下的模型配置
- 租户管理员（tenant_admin）：只能更新自己租户下的模型配置

**访问权限验证**：
- 系统会自动查询目标配置所属的租户
- 租户管理员尝试更新其他租户的配置时，将收到 403 权限不足错误
- 平台管理员可以更新任意租户的配置，无需额外验证

**参数说明**：
- id: 配置ID（UUID格式）
- name: 配置名称（可选）
- model: 模型标识（可选）
- baseUrl: API基础URL（可选）
- apiKey: API密钥（可选，将被加密存储）
- queryParams: 查询参数（可选，JSON格式）
 * @summary 更新模型配置
 */
  const putModelConfigurationsId = (
    { id }: PutModelConfigurationsIdPathParameters,
    updateModelConfigurationRequest: UpdateModelConfigurationRequest,
  ) => {
    return orvalMutator<ResponseDataModelModelConfiguration>({
      url: `/model-configurations/${id}`,
      method: 'PUT',
      headers: { 'Content-Type': 'application/json' },
      data: updateModelConfigurationRequest,
    });
  };
  /**
 * 启用或禁用模型配置

**权限要求**：
- 平台管理员（system_admin）：可以更新任意租户下的模型配置状态
- 租户管理员（tenant_admin）：只能更新自己租户下的模型配置状态

**访问权限验证**：
- 系统会自动查询目标配置所属的租户
- 租户管理员尝试更新其他租户的配置状态时，将收到 403 权限不足错误
- 平台管理员可以更新任意租户的配置状态，无需额外验证

**功能说明**：
- 启用配置（status=enabled）：配置可以被使用
- 禁用配置（status=disabled）：配置将不可用

**参数说明**：
- id: 配置ID（UUID格式）
- status: 配置状态（enabled=启用，disabled=禁用）
 * @summary 更新模型配置状态
 */
  const patchModelConfigurationsIdStatus = (
    { id }: PatchModelConfigurationsIdStatusPathParameters,
    updateStatusRequest: UpdateStatusRequest,
  ) => {
    return orvalMutator<ResponseDataAny>({
      url: `/model-configurations/${id}/status`,
      method: 'PATCH',
      headers: { 'Content-Type': 'application/json' },
      data: updateStatusRequest,
    });
  };
  /**
 * 验证模型配置是否可以正确连接到提供商

**权限要求**：
- 平台管理员（system_admin）：可以验证任意租户下的模型配置
- 租户管理员（tenant_admin）：只能验证自己租户下的模型配置

**访问权限验证**：
- 系统会自动查询目标配置所属的租户
- 租户管理员尝试验证其他租户的配置时，将收到 403 权限不足错误
- 平台管理员可以验证任意租户的配置，无需额外验证

**功能说明**：
- 使用配置的参数尝试连接到模型提供商
- 验证请求设置30秒超时
- 返回验证结果，包括成功/失败状态和详细信息

**参数说明**：
- id: 配置ID（UUID格式）
 * @summary 验证模型配置
 */
  const postModelConfigurationsIdValidate = ({
    id,
  }: PostModelConfigurationsIdValidatePathParameters) => {
    return orvalMutator<ResponseDataModelValidationResult>({
      url: `/model-configurations/${id}/validate`,
      method: 'POST',
    });
  };
  /**
 * 获取当前租户下所有可用的模型配置（已启用且未删除）

**权限要求**：
- 所有已认证用户都可以调用此接口
- 自动返回当前用户所属租户下的可用配置

**功能说明**：
- 仅返回已启用（is_enabled=true）且未删除（is_deleted=false）的配置
- 返回的配置不包含敏感信息（API密钥、查询参数等）
- 用于前端展示可选的模型列表

**返回字段**：
- id: 配置ID
- name: 配置名称
- model: 模型标识
- modelProvider: 模型提供商
 * @summary 获取可用模型配置列表
 */
  const getModelConfigurationsAvailable = () => {
    return orvalMutator<ResponseDataArrayModelModelConfiguration>({
      url: `/model-configurations/available`,
      method: 'GET',
    });
  };
  return {
    getModelConfigurations,
    postModelConfigurations,
    deleteModelConfigurationsId,
    getModelConfigurationsId,
    putModelConfigurationsId,
    patchModelConfigurationsIdStatus,
    postModelConfigurationsIdValidate,
    getModelConfigurationsAvailable,
  };
};
export type GetModelConfigurationsResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getModelConfiguration>['getModelConfigurations']>>
>;
export type PostModelConfigurationsResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getModelConfiguration>['postModelConfigurations']>>
>;
export type DeleteModelConfigurationsIdResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getModelConfiguration>['deleteModelConfigurationsId']>>
>;
export type GetModelConfigurationsIdResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getModelConfiguration>['getModelConfigurationsId']>>
>;
export type PutModelConfigurationsIdResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getModelConfiguration>['putModelConfigurationsId']>>
>;
export type PatchModelConfigurationsIdStatusResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getModelConfiguration>['patchModelConfigurationsIdStatus']>>
>;
export type PostModelConfigurationsIdValidateResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getModelConfiguration>['postModelConfigurationsIdValidate']>>
>;
export type GetModelConfigurationsAvailableResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getModelConfiguration>['getModelConfigurationsAvailable']>>
>;
