/**
 * Generated by orval v7.16.0 🍺
 * Do not edit manually.
 * Genkit AI Service API
 * AI 模型提供商管理服务 API 文档
提供模型提供商、模型信息和参数规则的查询接口
 * OpenAPI spec version: 1.0.0
 */
import type {
  AIQARequestSwaggerBody,
  AISearchRequestSwagger,
  LexiangAIQADataResponse,
  LexiangAISearchDataResponse,
} from '../../../types/api';
import { orvalMutator } from '../../../utils/orval-mutator';

export const getLexiangAi = () => {
  /**
   * 向乐享AI助手提问，获取基于知识库内容的回答
   * @summary AI问答
   */
  const postLexiangAiQa = (aIQARequestSwaggerBody: AIQARequestSwaggerBody) => {
    return orvalMutator<LexiangAIQADataResponse>({
      url: `/lexiang/ai/qa`,
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      data: aIQARequestSwaggerBody,
    });
  };
  /**
   * 向乐享AI助手提问，以 Server-Sent Events 流式返回回答
   * @summary AI问答（流式）
   */
  const postLexiangAiQaStream = (aIQARequestSwaggerBody: AIQARequestSwaggerBody) => {
    return orvalMutator<string>({
      url: `/lexiang/ai/qa/stream`,
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      data: aIQARequestSwaggerBody,
    });
  };
  /**
   * 使用AI在知识库中搜索相关文档
   * @summary AI搜索
   */
  const postLexiangAiSearch = (aISearchRequestSwagger: AISearchRequestSwagger) => {
    return orvalMutator<LexiangAISearchDataResponse>({
      url: `/lexiang/ai/search`,
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      data: aISearchRequestSwagger,
    });
  };
  return { postLexiangAiQa, postLexiangAiQaStream, postLexiangAiSearch };
};
export type PostLexiangAiQaResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getLexiangAi>['postLexiangAiQa']>>
>;
export type PostLexiangAiQaStreamResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getLexiangAi>['postLexiangAiQaStream']>>
>;
export type PostLexiangAiSearchResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getLexiangAi>['postLexiangAiSearch']>>
>;
