/**
 * Generated by orval v7.16.0 🍺
 * Do not edit manually.
 * Genkit AI Service API
 * AI 模型提供商管理服务 API 文档
提供模型提供商、模型信息和参数规则的查询接口
 * OpenAPI spec version: 1.0.0
 */
import type {
  AnyDataResponse,
  CreateFileEntryRequestSwagger,
  CreateFolderRequestSwagger,
  DeleteLexiangEntriesIdPathParameters,
  GetLexiangEntriesIdContentPathParameters,
  GetLexiangEntriesIdPathParameters,
  GetLexiangEntriesParams,
  LexiangEntryContentDataResponse,
  LexiangEntryDataResponse,
  LexiangEntryListDataResponse,
  PostLexiangEntriesIdReuploadPathParameters,
  ReuploadFileRequestSwagger,
} from '../../../types/api';
import { orvalMutator } from '../../../utils/orval-mutator';

export const getLexiangEntries = () => {
  /**
   * 获取指定知识库或父节点下的知识节点列表
   * @summary 获取知识节点列表
   */
  const getLexiangEntries = (params: GetLexiangEntriesParams) => {
    return orvalMutator<LexiangEntryListDataResponse>({
      url: `/lexiang/entries`,
      method: 'GET',
      params,
    });
  };
  /**
   * 删除指定的知识节点
   * @summary 删除知识节点
   */
  const deleteLexiangEntriesId = ({ id }: DeleteLexiangEntriesIdPathParameters) => {
    return orvalMutator<AnyDataResponse>({ url: `/lexiang/entries/${id}`, method: 'DELETE' });
  };
  /**
   * 根据节点ID获取详细信息
   * @summary 获取知识节点详情
   */
  const getLexiangEntriesId = ({ id }: GetLexiangEntriesIdPathParameters) => {
    return orvalMutator<LexiangEntryDataResponse>({ url: `/lexiang/entries/${id}`, method: 'GET' });
  };
  /**
   * 获取线上文档的 HTML 内容（仅支持 entry_type=page 的节点）
   * @summary 获取线上文档内容
   */
  const getLexiangEntriesIdContent = ({ id }: GetLexiangEntriesIdContentPathParameters) => {
    return orvalMutator<LexiangEntryContentDataResponse>({
      url: `/lexiang/entries/${id}/content`,
      method: 'GET',
    });
  };
  /**
   * 更新指定节点的文件内容
   * @summary 重新上传文件
   */
  const postLexiangEntriesIdReupload = (
    { id }: PostLexiangEntriesIdReuploadPathParameters,
    reuploadFileRequestSwagger: ReuploadFileRequestSwagger,
  ) => {
    return orvalMutator<AnyDataResponse>({
      url: `/lexiang/entries/${id}/reupload`,
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      data: reuploadFileRequestSwagger,
    });
  };
  /**
   * 使用上传的 state 创建文件类型的知识节点
   * @summary 创建文件节点
   */
  const postLexiangEntriesFile = (createFileEntryRequestSwagger: CreateFileEntryRequestSwagger) => {
    return orvalMutator<LexiangEntryDataResponse>({
      url: `/lexiang/entries/file`,
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      data: createFileEntryRequestSwagger,
    });
  };
  /**
   * 在指定父节点下创建文件夹
   * @summary 创建文件夹
   */
  const postLexiangEntriesFolder = (createFolderRequestSwagger: CreateFolderRequestSwagger) => {
    return orvalMutator<LexiangEntryDataResponse>({
      url: `/lexiang/entries/folder`,
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      data: createFolderRequestSwagger,
    });
  };
  return {
    getLexiangEntries,
    deleteLexiangEntriesId,
    getLexiangEntriesId,
    getLexiangEntriesIdContent,
    postLexiangEntriesIdReupload,
    postLexiangEntriesFile,
    postLexiangEntriesFolder,
  };
};
export type GetLexiangEntriesResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getLexiangEntries>['getLexiangEntries']>>
>;
export type DeleteLexiangEntriesIdResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getLexiangEntries>['deleteLexiangEntriesId']>>
>;
export type GetLexiangEntriesIdResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getLexiangEntries>['getLexiangEntriesId']>>
>;
export type GetLexiangEntriesIdContentResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getLexiangEntries>['getLexiangEntriesIdContent']>>
>;
export type PostLexiangEntriesIdReuploadResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getLexiangEntries>['postLexiangEntriesIdReupload']>>
>;
export type PostLexiangEntriesFileResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getLexiangEntries>['postLexiangEntriesFile']>>
>;
export type PostLexiangEntriesFolderResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getLexiangEntries>['postLexiangEntriesFolder']>>
>;
