/**
 * Generated by orval v7.14.0 🍺
 * Do not edit manually.
 * Genkit AI Service API
 * AI 模型提供商管理服务 API 文档
提供模型提供商、模型信息和参数规则的查询接口
 * OpenAPI spec version: 1.0.0
 */
import type {
  AnyDataResponse,
  CreateTenantRequest,
  DeleteTenantsIdPathParameters,
  GetTenantsIdPathParameters,
  GetTenantsParams,
  PutTenantsIdPathParameters,
  TenantDataResponse,
  TenantListResponse,
  UpdateTenantRequest,
} from '../../../types/api'

import { orvalMutator } from '../../../utils/orval-mutator'

export const getTenantManagement = () => {
  /**
   * 获取租户列表，支持分页（需要管理员权限）
   * @summary 获取租户列表
   */
  const getTenants = (params: GetTenantsParams) => {
    return orvalMutator<TenantListResponse>({
      url: `/tenants`,
      method: 'GET',
      params,
    })
  }
  /**
   * 创建新的租户（需要管理员权限）
   * @summary 创建租户
   */
  const postTenants = (createTenantRequest: CreateTenantRequest) => {
    return orvalMutator<TenantDataResponse>({
      url: `/tenants`,
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      data: createTenantRequest,
    })
  }
  /**
   * 软删除指定的租户（需要管理员权限）
   * @summary 删除租户
   */
  const deleteTenantsId = ({ id }: DeleteTenantsIdPathParameters) => {
    return orvalMutator<AnyDataResponse>({
      url: `/tenants/${id}`,
      method: 'DELETE',
    })
  }
  /**
   * 根据租户ID获取租户详细信息（需要管理员权限）
   * @summary 获取租户详情
   */
  const getTenantsId = ({ id }: GetTenantsIdPathParameters) => {
    return orvalMutator<TenantDataResponse>({
      url: `/tenants/${id}`,
      method: 'GET',
    })
  }
  /**
   * 更新租户信息（需要管理员权限）
   * @summary 更新租户
   */
  const putTenantsId = (
    { id }: PutTenantsIdPathParameters,
    updateTenantRequest: UpdateTenantRequest,
  ) => {
    return orvalMutator<TenantDataResponse>({
      url: `/tenants/${id}`,
      method: 'PUT',
      headers: { 'Content-Type': 'application/json' },
      data: updateTenantRequest,
    })
  }
  return {
    getTenants,
    postTenants,
    deleteTenantsId,
    getTenantsId,
    putTenantsId,
  }
}
export type GetTenantsResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getTenantManagement>['getTenants']>>
>
export type PostTenantsResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getTenantManagement>['postTenants']>>
>
export type DeleteTenantsIdResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getTenantManagement>['deleteTenantsId']>>
>
export type GetTenantsIdResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getTenantManagement>['getTenantsId']>>
>
export type PutTenantsIdResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getTenantManagement>['putTenantsId']>>
>
