/**
 * Generated by orval v7.14.0 🍺
 * Do not edit manually.
 * Genkit AI Service API
 * AI 模型提供商管理服务 API 文档
提供模型提供商、模型信息和参数规则的查询接口
 * OpenAPI spec version: 1.0.0
 */
import type {
  AnyDataResponse,
  GetChatMessagesIdPathParameters,
  GetChatSessionsIdMessagesParams,
  GetChatSessionsIdMessagesPathParameters,
  MessageDetailDataResponse,
  MessageDetailListResponse,
  MessageResponseData,
  PostChatMessagesIdAbortPathParameters,
  PostChatSessionsIdMessagesPathParameters,
  PostChatSessionsIdMessagesStreamPathParameters,
  SendMessageRequestBody,
} from '../../../types/api';
import { orvalMutator } from '../../../utils/orval-mutator';

export const getMessages = () => {
  /**
   * 根据消息ID获取消息的详细信息
   * @summary 获取消息详情
   */
  const getChatMessagesId = ({ id }: GetChatMessagesIdPathParameters) => {
    return orvalMutator<MessageDetailDataResponse>({ url: `/chat/messages/${id}`, method: 'GET' });
  };
  /**
   * 中止指定消息的AI生成过程
   * @summary 中止消息生成
   */
  const postChatMessagesIdAbort = ({ id }: PostChatMessagesIdAbortPathParameters) => {
    return orvalMutator<AnyDataResponse>({ url: `/chat/messages/${id}/abort`, method: 'POST' });
  };
  /**
   * 获取指定会话的消息历史，支持分页
   * @summary 获取消息历史
   */
  const getChatSessionsIdMessages = (
    { id }: GetChatSessionsIdMessagesPathParameters,
    params: GetChatSessionsIdMessagesParams,
  ) => {
    return orvalMutator<MessageDetailListResponse>({
      url: `/chat/sessions/${id}/messages`,
      method: 'GET',
      params,
    });
  };
  /**
   * 在指定会话中发送消息并获取AI回复
   * @summary 发送消息
   */
  const postChatSessionsIdMessages = (
    { id }: PostChatSessionsIdMessagesPathParameters,
    sendMessageRequestBody: SendMessageRequestBody,
  ) => {
    return orvalMutator<MessageResponseData>({
      url: `/chat/sessions/${id}/messages`,
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      data: sendMessageRequestBody,
    });
  };
  /**
   * 在指定会话中发送消息并以 SSE 流式返回 AI 回复
   * @summary 流式发送消息
   */
  const postChatSessionsIdMessagesStream = (
    { id }: PostChatSessionsIdMessagesStreamPathParameters,
    sendMessageRequestBody: SendMessageRequestBody,
  ) => {
    return orvalMutator<string>({
      url: `/chat/sessions/${id}/messages/stream`,
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      data: sendMessageRequestBody,
    });
  };
  return {
    getChatMessagesId,
    postChatMessagesIdAbort,
    getChatSessionsIdMessages,
    postChatSessionsIdMessages,
    postChatSessionsIdMessagesStream,
  };
};
export type GetChatMessagesIdResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getMessages>['getChatMessagesId']>>
>;
export type PostChatMessagesIdAbortResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getMessages>['postChatMessagesIdAbort']>>
>;
export type GetChatSessionsIdMessagesResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getMessages>['getChatSessionsIdMessages']>>
>;
export type PostChatSessionsIdMessagesResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getMessages>['postChatSessionsIdMessages']>>
>;
export type PostChatSessionsIdMessagesStreamResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getMessages>['postChatSessionsIdMessagesStream']>>
>;
