/**
 * Generated by orval v7.14.0 🍺
 * Do not edit manually.
 * Genkit AI Service API
 * AI 模型提供商管理服务 API 文档
提供模型提供商、模型信息和参数规则的查询接口
 * OpenAPI spec version: 1.0.0
 */
import type {
  AnyDataResponse,
  CreateUserRequestBody,
  DeleteUsersIdPathParameters,
  GetUsersIdPathParameters,
  GetUsersParams,
  PutUsersIdPathParameters,
  UpdateUserRequest,
  UserDataResponse,
  UserListResponse,
} from '../../../types/api'

import { orvalMutator } from '../../../utils/orval-mutator'

export const getUserManagement = () => {
  /**
   * 获取当前租户下的用户列表，支持分页（需要租户管理员权限）
   * @summary 获取用户列表
   */
  const getUsers = (params: GetUsersParams) => {
    return orvalMutator<UserListResponse>({
      url: `/users`,
      method: 'GET',
      params,
    })
  }
  /**
   * 在指定租户下创建新用户（需要租户管理员权限）
   * @summary 创建用户
   */
  const postUsers = (createUserRequestBody: CreateUserRequestBody) => {
    return orvalMutator<UserDataResponse>({
      url: `/users`,
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      data: createUserRequestBody,
    })
  }
  /**
   * 软删除指定的用户（需要租户管理员权限）
   * @summary 删除用户
   */
  const deleteUsersId = ({ id }: DeleteUsersIdPathParameters) => {
    return orvalMutator<AnyDataResponse>({
      url: `/users/${id}`,
      method: 'DELETE',
    })
  }
  /**
   * 根据用户ID获取用户详细信息（需要租户管理员权限）
   * @summary 获取用户详情
   */
  const getUsersId = ({ id }: GetUsersIdPathParameters) => {
    return orvalMutator<UserDataResponse>({
      url: `/users/${id}`,
      method: 'GET',
    })
  }
  /**
   * 更新用户信息（需要租户管理员权限）
   * @summary 更新用户
   */
  const putUsersId = (
    { id }: PutUsersIdPathParameters,
    updateUserRequest: UpdateUserRequest,
  ) => {
    return orvalMutator<UserDataResponse>({
      url: `/users/${id}`,
      method: 'PUT',
      headers: { 'Content-Type': 'application/json' },
      data: updateUserRequest,
    })
  }
  return { getUsers, postUsers, deleteUsersId, getUsersId, putUsersId }
}
export type GetUsersResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getUserManagement>['getUsers']>>
>
export type PostUsersResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getUserManagement>['postUsers']>>
>
export type DeleteUsersIdResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getUserManagement>['deleteUsersId']>>
>
export type GetUsersIdResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getUserManagement>['getUsersId']>>
>
export type PutUsersIdResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getUserManagement>['putUsersId']>>
>
