/**
 * Generated by orval v7.16.0 🍺
 * Do not edit manually.
 * Genkit AI Service API
 * AI 模型提供商管理服务 API 文档
提供模型提供商、模型信息和参数规则的查询接口
 * OpenAPI spec version: 1.0.0
 */
import type { AIQARequestSwaggerLanguage } from './aIQARequestSwaggerLanguage';
import type { AIQARequestSwaggerQaMode } from './aIQARequestSwaggerQaMode';
import type { AITargetSwagger } from './aITargetSwagger';

export interface AIQARequestSwagger {
  anonymousStaffId?: string;
  language?: AIQARequestSwaggerLanguage;
  maxChars?: number;
  newSession?: boolean;
  qaMode?: AIQARequestSwaggerQaMode;
  /** @maxLength 1024 */
  query: string;
  sessionId?: string;
  skipFaq?: boolean;
  stream?: boolean;
  targets?: AITargetSwagger[];
}
