/**
 * Generated by orval v7.16.0 🍺
 * Do not edit manually.
 * Genkit AI Service API
 * AI 模型提供商管理服务 API 文档
提供模型提供商、模型信息和参数规则的查询接口
 * OpenAPI spec version: 1.0.0
 */

export type AIQARequestSwaggerQaMode =
  (typeof AIQARequestSwaggerQaMode)[keyof typeof AIQARequestSwaggerQaMode];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const AIQARequestSwaggerQaMode = {
  normal: 'normal',
  'normal-ds-v3': 'normal-ds-v3',
  'normal-ds-v31': 'normal-ds-v3.1',
  reasoning: 'reasoning',
  'reasoning-ds-v31': 'reasoning-ds-v3.1',
  research: 'research',
  'research-ds-v31': 'research-ds-v3.1',
} as const;
