/**
 * Generated by orval v7.16.0 🍺
 * Do not edit manually.
 * Genkit AI Service API
 * AI 模型提供商管理服务 API 文档
提供模型提供商、模型信息和参数规则的查询接口
 * OpenAPI spec version: 1.0.0
 */

export interface AuthAuditItem {
  /** 事件发生时间 */
  createdAt?: string;
  /** 事件类型 */
  event?: string;
  /** 审计日志ID */
  id?: string;
  /** 客户端IP地址 */
  ip?: string;
  /** 事件元数据 */
  meta?: unknown;
  /** 租户ID */
  tenantId?: string;
  /** 用户代理字符串 */
  userAgent?: string;
  /** 用户ID */
  userId?: string;
}
