/**
 * Generated by orval v7.16.0 🍺
 * Do not edit manually.
 * Genkit AI Service API
 * AI 模型提供商管理服务 API 文档
提供模型提供商、模型信息和参数规则的查询接口
 * OpenAPI spec version: 1.0.0
 */
import type { ChatHistoryMessageRole } from './chatHistoryMessageRole';

/**
 * 历史对话中的单条消息
 */
export interface ChatHistoryMessage {
  /** 消息内容
@Description 消息的文本内容
@Example 你好 */
  content: string;
  /** 角色：user（用户）或 assistant（AI助手）
@Description 消息发送者的角色
@Example user */
  role: ChatHistoryMessageRole;
}
