/**
 * Generated by orval v7.16.0 🍺
 * Do not edit manually.
 * Genkit AI Service API
 * AI 模型提供商管理服务 API 文档
提供模型提供商、模型信息和参数规则的查询接口
 * OpenAPI spec version: 1.0.0
 */

/**
 * 角色：user（用户）或 assistant（AI助手）
@Description 消息发送者的角色
@Example user
 */
export type ChatHistoryMessageRole =
  (typeof ChatHistoryMessageRole)[keyof typeof ChatHistoryMessageRole];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ChatHistoryMessageRole = {
  user: 'user',
  assistant: 'assistant',
  system: 'system',
} as const;
