/**
 * Generated by orval v7.14.0 🍺
 * Do not edit manually.
 * Genkit AI Service API
 * AI 模型提供商管理服务 API 文档
提供模型提供商、模型信息和参数规则的查询接口
 * OpenAPI spec version: 1.0.0
 */
import type { CreateTenantWithAdminRequestTenantMetadata } from './createTenantWithAdminRequestTenantMetadata'

export interface CreateTenantWithAdminRequest {
  /**
   * 管理员显示名称（可选，最多255字符）
   * @maxLength 255
   */
  adminDisplayName?: string
  /** 管理员邮箱（可选，默认为 admin@{tenantDomain}） */
  adminEmail?: string
  /**
   * 租户域名（必填，最多255字符）
   * @maxLength 255
   */
  tenantDomain: string
  /** 租户元数据（可选，JSON对象） */
  tenantMetadata?: CreateTenantWithAdminRequestTenantMetadata
  /**
   * 租户名称（必填，1-255字符）
   * @minLength 1
   * @maxLength 255
   */
  tenantName: string
}
