/**
 * Generated by orval v7.14.0 🍺
 * Do not edit manually.
 * Genkit AI Service API
 * AI 模型提供商管理服务 API 文档
提供模型提供商、模型信息和参数规则的查询接口
 * OpenAPI spec version: 1.0.0
 */
import type { CredentialFormSchemaLabel } from './credentialFormSchemaLabel'
import type { FormOption } from './formOption'
import type { CredentialFormSchemaPlaceholder } from './credentialFormSchemaPlaceholder'

export interface CredentialFormSchema {
  /** 默认值 */
  default?: string
  /** 标签（多语言） */
  label?: CredentialFormSchemaLabel
  /** 选项列表 */
  options?: FormOption[]
  /** 占位符（多语言） */
  placeholder?: CredentialFormSchemaPlaceholder
  /** 是否必填 */
  required?: boolean
  /** 类型 */
  type?: string
  /** 变量名 */
  variable?: string
}
