/**
 * Generated by orval v7.14.0 🍺
 * Do not edit manually.
 * Genkit AI Service API
 * AI 模型提供商管理服务 API 文档
提供模型提供商、模型信息和参数规则的查询接口
 * OpenAPI spec version: 1.0.0
 */
import type { GenkitAiServiceInternalModelUser } from './genkitAiServiceInternalModelUser'

export interface GenkitAiServiceInternalModelLoginResponse {
  /** 访问令牌 */
  accessToken?: string
  /** 过期时间（秒） */
  expiresIn?: number
  /** 刷新令牌 */
  refreshToken?: string
  /** 令牌类型 */
  tokenType?: string
  /** 用户信息 */
  user?: GenkitAiServiceInternalModelUser
}
