/**
 * Generated by orval v7.14.0 🍺
 * Do not edit manually.
 * Genkit AI Service API
 * AI 模型提供商管理服务 API 文档
提供模型提供商、模型信息和参数规则的查询接口
 * OpenAPI spec version: 1.0.0
 */
import type { GenkitAiServiceInternalServiceHealthHealthStatusDependencies } from './genkitAiServiceInternalServiceHealthHealthStatusDependencies'

export interface GenkitAiServiceInternalServiceHealthHealthStatus {
  /** 依赖服务状态 */
  dependencies?: GenkitAiServiceInternalServiceHealthHealthStatusDependencies
  /** 整体状态：healthy, unhealthy */
  status?: string
  /** 运行时间 */
  uptime?: string
  /** 服务版本 */
  version?: string
}
