/**
 * Generated by orval v7.14.0 🍺
 * Do not edit manually.
 * Genkit AI Service API
 * AI 模型提供商管理服务 API 文档
提供模型提供商、模型信息和参数规则的查询接口
 * OpenAPI spec version: 1.0.0
 */
import type { GenkitAiServiceInternalModelCreateSessionRequestMeta } from './genkitAiServiceInternalModelCreateSessionRequestMeta'

export interface GenkitAiServiceInternalModelCreateSessionRequest {
  /** 元数据（可选） */
  meta?: GenkitAiServiceInternalModelCreateSessionRequestMeta
  /**
   * 模型名称
   * @maxLength 128
   */
  modelName: string
  /** 系统提示词（可选） */
  systemPrompt?: string
  /**
   * 温度参数（可选，0-2）
   * @minimum 0
   * @maximum 2
   */
  temperature?: number
  /**
   * 会话标题
   * @maxLength 255
   */
  title: string
  /**
   * TopP参数（可选，0-1）
   * @minimum 0
   * @maximum 1
   */
  topP?: number
}
