/**
 * Generated by orval v7.14.0 🍺
 * Do not edit manually.
 * Genkit AI Service API
 * AI 模型提供商管理服务 API 文档
提供模型提供商、模型信息和参数规则的查询接口
 * OpenAPI spec version: 1.0.0
 */
import type { GenkitAiServiceInternalModelProviderHelp } from './genkitAiServiceInternalModelProviderHelp'
import type { GenkitAiServiceInternalModelProviderIconLarge } from './genkitAiServiceInternalModelProviderIconLarge'
import type { GenkitAiServiceInternalModelProviderIconSmall } from './genkitAiServiceInternalModelProviderIconSmall'
import type { GenkitAiServiceInternalModelProviderLabel } from './genkitAiServiceInternalModelProviderLabel'
import type { GenkitAiServiceInternalModelCredentialSchema } from './genkitAiServiceInternalModelCredentialSchema'
import type { GenkitAiServiceInternalModelProviderModels } from './genkitAiServiceInternalModelProviderModels'

export interface GenkitAiServiceInternalModelProvider {
  /** 背景色 */
  background?: string
  /** 配置方法列表 */
  configurate_methods?: string[]
  /** 帮助信息 */
  help?: GenkitAiServiceInternalModelProviderHelp
  /** 大图标（多语言） */
  icon_large?: GenkitAiServiceInternalModelProviderIconLarge
  /** 小图标（多语言） */
  icon_small?: GenkitAiServiceInternalModelProviderIconSmall
  /** 提供商ID（从文件夹名称获取） */
  id?: string
  /** 多语言标签 */
  label?: GenkitAiServiceInternalModelProviderLabel
  /** 模型凭证配置 */
  model_credential_schema?: GenkitAiServiceInternalModelCredentialSchema
  /** 模型类型配置 */
  models?: GenkitAiServiceInternalModelProviderModels
  /** 提供商标识 */
  provider?: string
  /** 提供商凭证配置 */
  provider_credential_schema?: GenkitAiServiceInternalModelCredentialSchema
  /** 支持的模型类型列表 */
  supported_model_types?: string[]
}
