/**
 * Generated by orval v7.14.0 🍺
 * Do not edit manually.
 * Genkit AI Service API
 * AI 模型提供商管理服务 API 文档
提供模型提供商、模型信息和参数规则的查询接口
 * OpenAPI spec version: 1.0.0
 */
import type { GenkitAiServiceInternalModelSessionResponse } from './genkitAiServiceInternalModelSessionResponse'

export interface GenkitAiServiceInternalModelPaginationDataArrayGenkitAiServiceInternalModelSessionResponse {
  /** 数据 */
  data?: GenkitAiServiceInternalModelSessionResponse[]
  /** 当前页码 */
  pageNo?: number
  /** 每页大小 */
  pageSize?: number
  /** 总记录数 */
  totalCount?: number
  /** 总页数 */
  totalPage?: number
}
