/**
 * Generated by orval v7.14.0 🍺
 * Do not edit manually.
 * Genkit AI Service API
 * AI 模型提供商管理服务 API 文档
提供模型提供商、模型信息和参数规则的查询接口
 * OpenAPI spec version: 1.0.0
 */
import type { GenkitAiServiceInternalModelMessagePreview } from './genkitAiServiceInternalModelMessagePreview'
import type { GenkitAiServiceInternalModelSessionResponseMeta } from './genkitAiServiceInternalModelSessionResponseMeta'

export interface GenkitAiServiceInternalModelSessionResponse {
  /** 创建时间 */
  createdAt?: string
  /** 会话ID */
  id?: string
  /** 是否归档 */
  isArchived?: boolean
  /** 是否置顶 */
  isPinned?: boolean
  /** 最后一条消息 */
  lastMessage?: GenkitAiServiceInternalModelMessagePreview
  /** 消息数量 */
  messageCount?: number
  /** 元数据 */
  meta?: GenkitAiServiceInternalModelSessionResponseMeta
  /** 模型名称 */
  modelName?: string
  /** 系统提示词 */
  systemPrompt?: string
  /** 温度参数 */
  temperature?: number
  /** 会话标题 */
  title?: string
  /** TopP参数 */
  topP?: number
  /** 更新时间 */
  updatedAt?: string
  /** 用户ID */
  userId?: string
}
