/**
 * Generated by orval v7.14.0 🍺
 * Do not edit manually.
 * Genkit AI Service API
 * AI 模型提供商管理服务 API 文档
提供模型提供商、模型信息和参数规则的查询接口
 * OpenAPI spec version: 1.0.0
 */
import type { GenkitAiServiceInternalModelModelLabel } from './genkitAiServiceInternalModelModelLabel'
import type { GenkitAiServiceInternalModelModelProperties } from './genkitAiServiceInternalModelModelProperties'
import type { GenkitAiServiceInternalModelParameterRule } from './genkitAiServiceInternalModelParameterRule'
import type { GenkitAiServiceInternalModelPricing } from './genkitAiServiceInternalModelPricing'

export interface GenkitAiServiceInternalModelModel {
  /** 是否已弃用 */
  deprecated?: boolean
  /** 特性列表 */
  features?: string[]
  /** 多语言标签 */
  label?: GenkitAiServiceInternalModelModelLabel
  /** 模型标识 */
  model?: string
  /** 模型属性 */
  model_properties?: GenkitAiServiceInternalModelModelProperties
  /** 模型类型（llm、tts、text_embedding等） */
  model_type?: string
  /** 参数规则 */
  parameter_rules?: GenkitAiServiceInternalModelParameterRule[]
  /** 定价信息 */
  pricing?: GenkitAiServiceInternalModelPricing
}
