/**
 * Generated by orval v7.14.0 🍺
 * Do not edit manually.
 * Genkit AI Service API
 * AI 模型提供商管理服务 API 文档
提供模型提供商、模型信息和参数规则的查询接口
 * OpenAPI spec version: 1.0.0
 */
import type { GenkitAiServiceInternalModelMessage } from './genkitAiServiceInternalModelMessage'
import type { GenkitAiServiceInternalModelUsage } from './genkitAiServiceInternalModelUsage'

export interface GenkitAiServiceInternalModelMessageResponse {
  /** AI消息 */
  aiMessage?: GenkitAiServiceInternalModelMessage
  /** 消息ID */
  messageId?: string
  /** 模型名称 */
  model?: string
  /** 会话ID */
  sessionId?: string
  /** 使用统计 */
  usage?: GenkitAiServiceInternalModelUsage
  /** 用户消息 */
  userMessage?: GenkitAiServiceInternalModelMessage
}
