/**
 * Generated by orval v7.14.0 🍺
 * Do not edit manually.
 * Genkit AI Service API
 * AI 模型提供商管理服务 API 文档
提供模型提供商、模型信息和参数规则的查询接口
 * OpenAPI spec version: 1.0.0
 */

export interface GenkitAiServiceInternalModelChatOptions {
  /** 最大token数 */
  maxTokens?: number
  /**
   * 温度值，控制输出的随机性（0-2）
   * @minimum 0
   * @maximum 2
   */
  temperature?: number
  /** Top-K采样参数 */
  topK?: number
  /**
   * Top-P采样参数（0-1）
   * @minimum 0
   * @maximum 1
   */
  topP?: number
}
