/**
 * Generated by orval v7.14.0 🍺
 * Do not edit manually.
 * Genkit AI Service API
 * AI 模型提供商管理服务 API 文档
提供模型提供商、模型信息和参数规则的查询接口
 * OpenAPI spec version: 1.0.0
 */
import type { GetApiV1PlatformTenantsType } from './getApiV1PlatformTenantsType'

export type GetApiV1PlatformTenantsParams = {
  /**
   * 页码（从1开始）
   * @minimum 1
   */
  pageNo?: number
  /**
   * 每页大小（1-100）
   * @minimum 1
   * @maximum 100
   */
  pageSize?: number
  /**
   * 租户类型过滤
   */
  type?: GetApiV1PlatformTenantsType
}
