/**
 * Generated by orval v7.16.0 🍺
 * Do not edit manually.
 * Genkit AI Service API
 * AI 模型提供商管理服务 API 文档
提供模型提供商、模型信息和参数规则的查询接口
 * OpenAPI spec version: 1.0.0
 */

export type GetAuditAuthParams = {
  /**
   * 租户ID
   */
  tenantId?: string;
  /**
   * 用户ID
   */
  userId?: string;
  /**
   * 事件类型（login, logout, refresh, revoke, failed_login）
   */
  event?: string;
  /**
   * 开始时间（RFC3339格式）
   */
  startTime?: string;
  /**
   * 结束时间（RFC3339格式）
   */
  endTime?: string;
  /**
   * 页码
   */
  page?: number;
  /**
   * 每页大小
   */
  pageSize?: number;
};
