/**
 * Generated by orval v7.14.0 🍺
 * Do not edit manually.
 * Genkit AI Service API
 * AI 模型提供商管理服务 API 文档
提供模型提供商、模型信息和参数规则的查询接口
 * OpenAPI spec version: 1.0.0
 */

export type GetTenantsTenantIdUsersParams = {
  /**
   * 页码
   * @minimum 1
   */
  pageNo?: number
  /**
   * 每页大小
   * @minimum 1
   * @maximum 100
   */
  pageSize?: number
}
