/**
 * Generated by orval v7.14.0 🍺
 * Do not edit manually.
 * Genkit AI Service API
 * AI 模型提供商管理服务 API 文档
提供模型提供商、模型信息和参数规则的查询接口
 * OpenAPI spec version: 1.0.0
 */

export type GetUsersParams = {
  /**
   * 页码
   * @minimum 1
   */
  pageNo?: number;
  /**
   * 每页大小
   * @minimum 1
   * @maximum 100
   */
  pageSize?: number;
  /**
   * 租户ID（仅平台管理员可用）
   */
  tenantId?: string;
  /**
   * 搜索关键词（支持模糊匹配 displayName、phone、email）
   */
  search?: string;
  /**
   * 用户状态（true=启用，false=禁用）
   */
  isActive?: boolean;
};
