/**
 * Generated by orval v7.14.0 🍺
 * Do not edit manually.
 * Genkit AI Service API
 * AI 模型提供商管理服务 API 文档
提供模型提供商、模型信息和参数规则的查询接口
 * OpenAPI spec version: 1.0.0
 */
import type { GenkitAiServiceInternalModelUser } from './genkitAiServiceInternalModelUser'
import type { GenkitAiServiceInternalModelTenant } from './genkitAiServiceInternalModelTenant'

export interface InternalApiHandlerCreateTenantWithAdminResponse {
  /** 管理员初始密码（请妥善保管并建议首次登录后修改） */
  adminPassword?: string
  /** 管理员用户信息 */
  adminUser?: GenkitAiServiceInternalModelUser
  /** 租户信息 */
  tenant?: GenkitAiServiceInternalModelTenant
}
