/**
 * Generated by orval v7.14.0 🍺
 * Do not edit manually.
 * Genkit AI Service API
 * AI 模型提供商管理服务 API 文档
提供模型提供商、模型信息和参数规则的查询接口
 * OpenAPI spec version: 1.0.0
 */
import type { LoginResponse } from './loginResponse';

export interface LoginDataResponse {
  /** 响应代码 */
  code?: number;
  /** 响应数据 */
  data?: LoginResponse;
  /** 响应信息 */
  message?: string;
  /** 追踪ID（用于全链路追踪和问题排查） */
  traceId?: string;
}
