/**
 * Generated by orval v7.16.0 🍺
 * Do not edit manually.
 * Genkit AI Service API
 * AI 模型提供商管理服务 API 文档
提供模型提供商、模型信息和参数规则的查询接口
 * OpenAPI spec version: 1.0.0
 */
import type { MessageDetailResponseMeta } from './messageDetailResponseMeta';
import type { MessageDetailResponseToolCalls } from './messageDetailResponseToolCalls';

export interface MessageDetailResponse {
  /** 消息内容 */
  content?: string;
  /** 创建时间 */
  createdAt?: string;
  /** 错误信息 */
  error?: string;
  /** 消息ID */
  id?: string;
  /** 元数据 */
  meta?: MessageDetailResponseMeta;
  /** 角色 */
  role?: string;
  /** 序列号 */
  sequence?: number;
  /** 会话ID */
  sessionId?: string;
  /** Token数量 */
  tokens?: number;
  /** 工具调用 */
  toolCalls?: MessageDetailResponseToolCalls;
}
