/**
 * Generated by orval v7.16.0 🍺
 * Do not edit manually.
 * Genkit AI Service API
 * AI 模型提供商管理服务 API 文档
提供模型提供商、模型信息和参数规则的查询接口
 * OpenAPI spec version: 1.0.0
 */

export interface ModelConfiguration {
  /** API基础URL（可选，用于自定义端点） */
  baseUrl?: string;
  createdAt?: string;
  /** 创建信息 */
  createdBy?: string;
  /** 主键，UUID类型 */
  id?: string;
  /** 是否启用 */
  isEnabled?: boolean;
  /** 模型标识（如：gpt-4、claude-3-opus等） */
  model?: string;
  /** 模型提供商枚举 */
  modelProvider?: string;
  /** 配置名称 */
  name?: string;
  /** 查询参数（JSON格式，可选） */
  queryParams?: string;
  /** 租户ID，外键关联 */
  tenantId?: string;
  updatedAt?: string;
  /** 更新信息 */
  updatedBy?: string;
}
