/**
 * Generated by orval v7.14.0 🍺
 * Do not edit manually.
 * Genkit AI Service API
 * AI 模型提供商管理服务 API 文档
提供模型提供商、模型信息和参数规则的查询接口
 * OpenAPI spec version: 1.0.0
 */
import type { ParameterRuleHelp } from './parameterRuleHelp';
import type { ParameterRuleLabel } from './parameterRuleLabel';

export interface ParameterRule {
  /** 默认值 */
  default?: unknown;
  /** 帮助信息（多语言） */
  help?: ParameterRuleHelp;
  /** 标签（多语言） */
  label?: ParameterRuleLabel;
  /** 最大值 */
  max?: unknown;
  /** 最小值 */
  min?: unknown;
  /** 参数名称 */
  name?: string;
  /** 选项列表 */
  options?: string[];
  /** 是否必填 */
  required?: boolean;
  /** 类型 */
  type?: string;
  /** 使用的模板 */
  use_template?: string;
}
