/**
 * Generated by orval v7.14.0 🍺
 * Do not edit manually.
 * Genkit AI Service API
 * AI 模型提供商管理服务 API 文档
提供模型提供商、模型信息和参数规则的查询接口
 * OpenAPI spec version: 1.0.0
 */
import type { ProviderHelpTitle } from './providerHelpTitle'
import type { ProviderHelpUrl } from './providerHelpUrl'

export interface ProviderHelp {
  /** 帮助标题（多语言） */
  title?: ProviderHelpTitle
  /** 帮助链接（多语言） */
  url?: ProviderHelpUrl
}
