/**
 * Generated by orval v7.14.0 🍺
 * Do not edit manually.
 * Genkit AI Service API
 * AI 模型提供商管理服务 API 文档
提供模型提供商、模型信息和参数规则的查询接口
 * OpenAPI spec version: 1.0.0
 */

/**
 * 租户类型：system=平台租户，tenant=业务租户
可选值：system（平台租户，系统级租户，只能有一个）, tenant（业务租户，普通租户）
 */
export type TenantType = (typeof TenantType)[keyof typeof TenantType]

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const TenantType = {
  system: 'system',
  tenant: 'tenant',
} as const
