/**
 * Generated by orval v7.14.0 🍺
 * Do not edit manually.
 * Genkit AI Service API
 * AI 模型提供商管理服务 API 文档
提供模型提供商、模型信息和参数规则的查询接口
 * OpenAPI spec version: 1.0.0
 */
import type { TenantMetadata } from './tenantMetadata'
import type { TenantType } from './tenantType'

/**
 * 租户信息，包含租户的基本信息和状态
 */
export interface Tenant {
  /** 创建时间 */
  createdAt?: string
  /** 创建者用户ID */
  createdBy?: string
  /** 租户域名，用于子域识别 */
  domain?: string
  /** 租户ID */
  id?: string
  /** 软删除标记 */
  isDeleted?: boolean
  /** 租户元数据，存储租户的自定义信息 */
  metadata?: TenantMetadata
  /** 租户名称 */
  name?: string
  /** 租户状态：true=启用，false=禁用
禁用的租户下的所有用户将无法登录 */
  status?: boolean
  /** 租户类型：system=平台租户，tenant=业务租户
可选值：system（平台租户，系统级租户，只能有一个）, tenant（业务租户，普通租户） */
  type?: TenantType
  /** 更新时间 */
  updatedAt?: string
}
