/**
 * Generated by orval v7.16.0 🍺
 * Do not edit manually.
 * Genkit AI Service API
 * AI 模型提供商管理服务 API 文档
提供模型提供商、模型信息和参数规则的查询接口
 * OpenAPI spec version: 1.0.0
 */
import type {
  LexiangUploadSignDataResponse,
  LexiangUploadStateDataResponse,
  PostLexiangUploadBody,
  UploadSignRequestSwagger,
} from '../../../types/api';
import { orvalMutator } from '../../../utils/orval-mutator';

export const getLexiangUpload = () => {
  /**
   * 完整的文件上传流程：获取签名 -> 上传到 COS -> 返回 state
   * @summary 上传文件
   */
  const postLexiangUpload = (postLexiangUploadBody: PostLexiangUploadBody) => {
    const formData = new FormData();
    formData.append(`file`, postLexiangUploadBody.file);
    formData.append(`mediaType`, postLexiangUploadBody.mediaType);

    return orvalMutator<LexiangUploadStateDataResponse>({
      url: `/lexiang/upload`,
      method: 'POST',
      headers: { 'Content-Type': 'multipart/form-data' },
      data: formData,
    });
  };
  /**
   * 获取文件上传到腾讯云 COS 的签名信息
   * @summary 获取上传签名
   */
  const postLexiangUploadSign = (uploadSignRequestSwagger: UploadSignRequestSwagger) => {
    return orvalMutator<LexiangUploadSignDataResponse>({
      url: `/lexiang/upload/sign`,
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      data: uploadSignRequestSwagger,
    });
  };
  return { postLexiangUpload, postLexiangUploadSign };
};
export type PostLexiangUploadResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getLexiangUpload>['postLexiangUpload']>>
>;
export type PostLexiangUploadSignResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getLexiangUpload>['postLexiangUploadSign']>>
>;
