/**
 * Generated by orval v7.16.0 🍺
 * Do not edit manually.
 * Genkit AI Service API
 * AI 模型提供商管理服务 API 文档
提供模型提供商、模型信息和参数规则的查询接口
 * OpenAPI spec version: 1.0.0
 */
import type {
  GetLexiangFeedbacksParams,
  LexiangFeedbackListDataResponse,
} from '../../../types/api';
import { orvalMutator } from '../../../utils/orval-mutator';

export const getLexiangFeedback = () => {
  /**
   * 获取指定知识库的用户反馈列表
   * @summary 获取知识反馈列表
   */
  const getLexiangFeedbacks = (params: GetLexiangFeedbacksParams) => {
    return orvalMutator<LexiangFeedbackListDataResponse>({
      url: `/lexiang/feedbacks`,
      method: 'GET',
      params,
    });
  };
  return { getLexiangFeedbacks };
};
export type GetLexiangFeedbacksResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getLexiangFeedback>['getLexiangFeedbacks']>>
>;
